### ISSUE TITLE
Make runnable inside gitlab-ci

### ISSUE THREAD

**Issue by Obito1903** [raffis/renovate-metrics#28]
Hello, I'm trying to use renovate-metrics as a job following the execution of renovate inside a gitlab-ci pipeline.

The issue i'm facing is that gitlab-ci require a shell with `chmod`, `touch` in order to execute the image.

Would it be possible to change the distroless image in order to have a shell with the tools required by gitlab ?
 
This is how the CI would look like in gitlab:

```yaml
default:
  tags:
    - docker
include:
  - remote: https://gitlab.com/renovate-bot/renovate-runner/-/raw/v17.270.7/templates/renovate.gitlab-ci.yml

stages:
  - deploy
  - metrics

metrics:
  stage: metrics
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  tags:
    - docker
  image: ghcr.io/raffis/renovate-metrics:latest
  script:
    - /usr/bin/renovate-metrics push --prometheus=https://prometheus-pushgateway --log-level=20 --file=renovate.json
```
